### ISSUE TITLE
start up but error , Is packages.json correct ? 

### ISSUE THREAD

**Issue by pythonwood** [pulilab/vue-people#134]
```
git clone 
cd frontend
npm install
nuxt 
```

-----------------

```
 ERROR  Invalid credentials Request failed with status code 404                                                                                                                  22:26:11

  at createError (node_modules/axios/lib/core/createError.js:16:15)
  at settle (node_modules/axios/lib/core/settle.js:17:12)
  at Unzip.handleStreamEnd (node_modules/axios/lib/adapters/http.js:244:11)
  at Unzip.emit (events.js:215:7)
  at Unzip.EventEmitter.emit (domain.js:475:20)
  at endReadableNT (_stream_readable.js:1184:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21) (repeated 13 times)
```

**maybe packages.json must update now ?**

**Comment by pythonwood** [comment]
ok, I fix it by  update nuxt.config.js：


```
baseURL: 'http://127.0.0.1:8000/',

config.proxy = {                                                                                                      
   '/api/': { target: 'http://localhost:8000/', secure: false },                                                       
   '/accounts/': { target: 'https//localhost:8000/', secure: false, cors: true }                                       
}; 
```
